import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader, SiteFooter } from "@/components/SiteChrome";
import { Framework } from "@/components/Framework";
import { PageCta } from "@/components/PageCta";
import { values } from "@/content/consulting";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Us — SYB Associates" }, { name: "description", content: "SYB Associates brings structure, analysis and practical action to complex business challenges." },
  { property: "og:title", content: "About Us — SYB Associates" }, { property: "og:description", content: "Better decisions. Better businesses." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/about" }, { name: "twitter:card", content: "summary_large_image" },
], links: [{ rel: "canonical", href: "/about" }] }), component: AboutPage });
const philosophy = ["Listen", "Understand", "Diagnose", "Act", "Measure"];
function AboutPage() { return <div className="min-h-screen bg-background text-foreground"><SiteHeader /><main><section className="border-b border-border/60 py-20 md:py-28"><div className="container-editorial"><p className="eyebrow">About Us</p><h1 className="mt-5 max-w-4xl font-display text-5xl md:text-7xl">Better Decisions.<br /><em className="text-navy">Better Businesses.</em></h1><div className="mt-10 max-w-3xl space-y-5 text-lg leading-relaxed text-muted-foreground"><p>SYB Associates was built around a simple belief: good consulting begins with understanding the problem.</p><p>We work with businesses to bring structure to complex challenges, combine data with business context and translate insights into practical action.</p><p>Our approach is deliberately problem-led rather than solution-led. We listen first, diagnose before prescribing, and focus on recommendations that can create measurable business value.</p></div></div></section><section className="py-20 md:py-28"><div className="container-editorial"><p className="eyebrow">Problem-Solving Philosophy</p>
<h2 className="mt-4 font-display text-4xl md:text-5xl">Clarity before action.</h2><div className="mt-6"><Framework items={philosophy} /></div></div>
</section><section className="border-y border-border/60 bg-navy-deep py-20 text-primary-foreground md:py-28"><div className="container-editorial grid gap-12 md:grid-cols-2"><div><p className="text-xs uppercase tracking-[0.2em] text-ice">Our Vision</p><p className="mt-4 font-display text-3xl leading-snug md:text-4xl">To help businesses add value to customers' lives, ensuring everyone's continued growth.</p></div><div><p className="text-xs uppercase tracking-[0.2em] text-ice">Our Mission</p><p className="mt-4 font-display text-3xl leading-snug md:text-4xl">To solve every business problem.</p></div></div></section><section className="py-20 md:py-28"><div className="container-editorial"><p className="eyebrow">Our Values</p><div className="mt-10 grid gap-px bg-border md:grid-cols-2">{values.map(([title,line,body]) => <article key={title} className="bg-background p-8"><h2 className="font-display text-3xl">{title}</h2><p className="mt-3 text-navy">{line}</p><p className="mt-4 leading-relaxed text-muted-foreground">{body}</p></article>)}</div></div></section><PageCta /></main><SiteFooter /></div> }