import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { SiteHeader, SiteFooter } from "@/components/SiteChrome";
import { PageCta } from "@/components/PageCta";
import { getIndustry } from "@/content/industries";

export const Route = createFileRoute("/industry/$industry")({
  loader: ({ params }) => { const industry = getIndustry(params.industry); if (!industry) throw notFound(); return industry; },
  head: ({ loaderData, params }) => ({ meta: [
    { title: loaderData ? `${loaderData.name} Consulting — SYB Associates` : "Industry Not Found — SYB Associates" },
    { name: "description", content: loaderData?.context ?? "Explore industry consulting from SYB Associates." },
    { property: "og:title", content: loaderData ? `${loaderData.name} Consulting — SYB Associates` : "Industry Consulting — SYB Associates" },
    { property: "og:description", content: loaderData?.context ?? "Industry-focused management consulting." },
    { property: "og:type", content: "website" }, { property: "og:url", content: `/industries/${params.industry}` }, { name: "twitter:card", content: "summary_large_image" },
    ...(!loaderData ? [{ name: "robots", content: "noindex" }] : []),
  ], links: loaderData ? [{ rel: "canonical", href: `/industries/${params.industry}` }] : [] }),
  notFoundComponent: () => <div className="min-h-screen bg-background"><SiteHeader /><main className="container-editorial py-28"><p className="eyebrow">Industries</p><h1 className="mt-4 font-display text-5xl">Industry not found.</h1><Link to="/industries" className="mt-8 inline-flex items-center gap-2 text-navy">View all industries <ArrowRight /></Link></main><SiteFooter /></div>,
  component: IndustryPage,
});
function IndustryPage() { const industry = Route.useLoaderData(); return <div className="min-h-screen bg-background text-foreground"><SiteHeader /><main><section className="border-b border-border/60 bg-navy-deep py-20 text-primary-foreground md:py-28"><div className="container-editorial"><p className="text-xs uppercase tracking-[0.2em] text-ice">Industry Perspective</p><h1 className="mt-5 max-w-4xl font-display text-5xl md:text-7xl">{industry.name}</h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-primary-foreground/70">{industry.context}</p></div></section><section className="py-20 md:py-28"><div className="container-editorial grid gap-12 md:grid-cols-12"><div className="md:col-span-4"><p className="eyebrow">Business Questions</p><h2 className="mt-4 font-display text-4xl">Questions we help address</h2></div><ol className="grid gap-px bg-border sm:grid-cols-2 md:col-span-7 md:col-start-6">{industry.questions.map((question, index) => <li key={question} className="bg-background p-6"><span className="text-xs text-navy">0{index + 1}</span><p className="mt-4 font-display text-xl leading-snug">{question}</p></li>)}</ol></div></section><section className="border-y border-border/60 bg-secondary py-20 md:py-28"><div className="container-editorial"><p className="eyebrow">Relevant Services</p><h2 className="mt-4 font-display text-4xl md:text-5xl">Connected commercial and operational support</h2><div className="mt-10 grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-4">{industry.services.map((service) => <Link key={service} to="/consulting-services" className="group bg-background p-6"><div className="font-display text-2xl">{service}</div><span className="mt-8 inline-flex items-center gap-2 text-sm text-navy">Explore <ArrowRight className="h-4 w-4" /></span></Link>)}</div></div></section><section className="py-20 md:py-28"><div className="container-editorial grid gap-10 md:grid-cols-12"><div className="md:col-span-4"><p className="eyebrow">Example Problem Statements</p><h2 className="mt-4 font-display text-4xl">From broad challenge to a clear decision.</h2></div><div className="space-y-4 md:col-span-7 md:col-start-6">{industry.questions.slice(0,3).map((q) => <div key={q} className="border-l-2 border-navy py-2 pl-5 text-lg">{q}</div>)}<p className="pt-4 text-sm text-muted-foreground">These are representative questions, not claims of prior client engagements.</p></div></div></section><section className="border-t border-border/60 py-16"><div className="container-editorial"><p className="eyebrow">Relevant Insights</p><p className="mt-3 text-muted-foreground">Our broader frameworks and practical perspectives apply across industries.</p><Link to="/insights" className="mt-5 inline-flex items-center gap-2 text-navy">Explore insights <ArrowRight /></Link></div></section><PageCta title={`Discuss a ${industry.name} Challenge`} /></main><SiteFooter /></div> }