import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { SiteHeader, SiteFooter } from "@/components/SiteChrome";
import { PageCta } from "@/components/PageCta";

export const Route = createFileRoute("/insights")({ head: () => ({ meta: [
  { title: "Insights — SYB Associates" }, { name: "description", content: "Practical frameworks and perspectives across strategy, profitability, revenue and operations." },
  { property: "og:title", content: "Insights — SYB Associates" }, { property: "og:description", content: "Structured perspectives for better business decisions." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/insights" }, { name: "twitter:card", content: "summary_large_image" },
], links: [{ rel: "canonical", href: "/insights" }] }), component: InsightsPage });
function InsightsPage() { return <div className="min-h-screen bg-background text-foreground"><SiteHeader /><main><section className="border-b border-border/60 py-20 md:py-28"><div className="container-editorial"><p className="eyebrow">Insights</p><h1 className="mt-5 max-w-4xl font-display text-5xl md:text-7xl">Structured perspectives for <em className="text-navy">better decisions.</em></h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-muted-foreground">Frameworks and practical thinking across commercial and operational questions.</p></div></section><section className="py-20 md:py-28"><div className="container-editorial"><article className="grid gap-10 border-y border-border py-10 md:grid-cols-12"><div className="md:col-span-3"><p className="eyebrow">Methodology</p></div><div className="md:col-span-7"><h2 className="font-display text-4xl">Operational Intelligence Transformation Framework™</h2><p className="mt-4 leading-relaxed text-muted-foreground">A structured approach to operational excellence, from discovery and diagnostic through implementation, measurement and continuous improvement.</p></div><div className="md:col-span-2 md:text-right"><Link to="/consultingMethodology" className="inline-flex items-center gap-2 text-navy">Read more <ArrowUpRight /></Link></div></article><div className="mt-12 max-w-2xl"><h2 className="font-display text-3xl">More perspectives are in development.</h2><p className="mt-4 text-muted-foreground">We will add concise, evidence-led articles without manufacturing claims or publishing for volume.</p></div></div></section><PageCta /></main><SiteFooter /></div> }